version: '3.4'

services:
  one-api:
    build: .
    image: "one-api:local"
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/oneapi:/data
      - ./logs:/app/logs
    environment:
      # 数据库配置 - 取消注释使用 MySQL，注释掉则使用 SQLite
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api
      
      # Redis 缓存配置 - 取消注释启用 Redis 缓存
      - REDIS_CONN_STRING=redis://redis
      
      # 会话密钥 - 必须修改为随机字符串
      - SESSION_SECRET=your_random_session_secret_here
      
      # 时区设置
      - TZ=Asia/Shanghai
      
      # 多机部署配置 - 从节点取消注释
      # - NODE_TYPE=slave
      # - SYNC_FREQUENCY=60
      # - FRONTEND_BASE_URL=https://your-domain.com
      
    depends_on:
      - redis
      - db
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "redis:7-alpine"
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  db:
    image: "mysql:8.0"
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 'OneAPI@justsong'
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: one-api
    command: --default-authentication-plugin=mysql_native_password